name: Create release from tag
on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'

jobs:
  build:
    name: Build
    uses: ./.github/workflows/build.yml

  release:
    name: Create release
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Upload Release assets
        uses: ncipollo/release-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          prerelease: true
          name: ${{ github.ref_name }}
          artifacts: '*.ipk,org.webosbrew.hyperion.ng.loader.manifest.json'
          artifactErrorsFailBuild: true
          allowUpdates: true
          omitPrereleaseDuringUpdate: true
          omitNameDuringUpdate: true
          omitDraftDuringUpdate: true
          omitBodyDuringUpdate: true
          replacesArtifacts: true
          generateReleaseNotes: true

